[package]
name = "rsclam"
version = "0.2.1"
authors = ["Tom Howard <info@tomhoward.codes>", "Najib Ishaq <nishaq@my.uri.edu>", "Noah Daniels <noah_daniels@uri.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ndarray = "^0.12.0"
petgraph = "^0.5.0"
distances = { git = "https://github.com/URI-ABD/distance" }
